var GameState=function(){this.playerSpeed=300;this.nextFire=0;this.fireRate=200;this.lastEnemySpawn=0;this.timeBetweenEnemySpawn=1E4;this.canShoot=this.spawnEnemies=!0;this.info=new Info;this.hasResetAmmo=!0;this.godMode=!1;this.godModeEndTime};
GameState.prototype={preload:function(){this.load.spritesheet("player","res/textures/player.png",64,64);this.load.spritesheet("enemy","res/textures/enemy.png",64,32);this.load.image("platform","res/textures/platform.png");this.load.image("background","res/textures/background.png");this.load.image("portal","res/textures/portal.png");this.load.image("bullet","res/textures/bullet.png");this.load.image("hud","res/textures/hud.png");this.load.audio("kill","res/audio/kill.wav");this.load.audio("jump","res/audio/jump.wav");
this.load.audio("hurt","res/audio/hurt.wav");game.time.advancedTiming=!0},create:function(){this.physics.startSystem(Phaser.Physics.ARCADE);this.world.setBounds(0,0,2E3,1E3);this.info.reset();this.canShoot=!0;this.add.sprite(0,0,"background").fixedToCamera=!0;this.platforms=this.add.group();this.platforms.enableBody=!0;var a=this.platforms.create(50,this.world.height/2,"platform");a.scale.x=100;a.body.immovable=!0;a=this.platforms.create(1200,this.world.height/2+50,"platform");a.scale.x=30;a.body.immovable=
!0;this.platform=this.platforms.create(1600,this.world.height-300,"platform");this.platform.scale.x=30;this.platform.body.immovable=!0;this.portal=this.add.sprite(this.world.width/2,this.world.height/2-400,"portal");this.physics.arcade.enable(this.portal);this.player=this.add.sprite(this.world.width/2,this.world.height/2-200,"player");this.physics.arcade.enable(this.player);this.player.scale.setTo(2,2);this.player.body.bounce.y=.15;this.player.body.gravity.y=500;this.physics.arcade.enable(this.player);
this.player.body.collideWorldBounds=!0;this.player.animations.add("left",[0,1,2],10,!0);this.player.animations.add("right",[3,4,5],10,!0);this.enemies=this.add.group();this.enemies.enableBody=!0;this.bullets=this.add.group();this.bullets.enableBody=!0;this.bullets.physicsBodyType=Phaser.Physics.ARCADE;this.bullets.createMultiple(50,"bullet");this.bullets.setAll("checkWorldBounds",!0);this.bullets.setAll("outOfBoundsKill",!0);this.cursors=this.input.keyboard.createCursorKeys();this.camera.follow(this.player);
this.hud=this.add.sprite(0,HEIGHT-50,"hud");this.hud.fixedToCamera=!0;this.info.createText(this);this.reloadTime=this.time.now;this.killSound=this.add.audio("kill");this.jumpSound=this.add.audio("jump");this.hurtSound=this.add.audio("hurt");this.nextEnemySpawnTime=this.time.now+3E3;this.startTime=game.time.now;this.input.onDown.add(this.shoot,this);a={font:"20px Arial",fill:"#000000",align:"center"};this.difficultyText=this.add.text(WIDTH-250,10,"Could do better in my sleep",a);this.difficultyText.fixedToCamera=
!0;a={font:"25px Arial",fill:"#e7be1b",align:"center"};this.godModeText=this.add.text(WIDTH/2-150,HEIGHT/2-100,"",a);this.godModeText.fixedToCamera=!0;this.godModeText.visible=!1},update:function(){this.physics.arcade.collide(this.player,this.platforms);this.physics.arcade.collide(this.enemies,this.platforms);this.physics.arcade.overlap(this.platforms,this.bullets,function(a,b){b.kill()},null,this);this.godMode||this.physics.arcade.overlap(this.player,this.enemies,function(a,b){this.info.health=5<
this.info.monstersKilled?this.info.health-this.info.monstersKilled/5:this.info.health-.5;this.hurtSound.isPlaying||this.hurtSound.play()},null,this);this.physics.arcade.overlap(this.bullets,this.enemies,function(a,b){a.kill();b.destroy();++this.info.monstersKilled;--this.info.aliveMonsters;this.killSound.play()},null,this);this.godMode&&this.physics.arcade.overlap(this.player,this.enemies,function(a,b){b.destroy();++this.info.monstersKilled;--this.info.aliveMonsters;this.killSound.play()},null,this);
this.info.updateText();this.pollInput();0>=this.info.health&&(this.canShoot=!1,this.info.health="DEAD",this.player.destroy(),infoForDeathState=this.info,game.state.start("death screen"));0>=this.info.ammo&&this.reload();this.tryToSpawnEnemies("enemy");this.enemies.forEach(this.moveEnemies,this);this.godMode?(this.time.now>this.godModeEndTime&&(this.godMode=!1),this.godModeText.visible=!0,this.godModeText.text="God Mode: "+(this.godModeEndTime-this.time.now)+"\nMonsters dissolve when touched\nJump in mid-air!"):
this.godModeText.visible=!1;0==this.info.monstersKilled%30&&0!==this.info.monstersKilled&&(this.godMode=!0,this.godModeEndTime=this.time.now+100*this.info.monstersKilled);DEBUG&&(game.debug.spriteCoords(this.player,32,32),game.debug.spriteCoords(this.godModeText,32,300),game.debug.text(game.time.fps,2,15,"#00ff00"))},shoot:function(){if(this.time.now>this.nextFire&&0<this.bullets.countDead()&&this.canShoot&&this.time.now>this.reloadTime){this.nextFire=this.time.now+this.fireRate;var a=this.bullets.getFirstDead();
"left"==this.direction?a.reset(this.player.x+20,this.player.y+64):a.reset(this.player.x+100,this.player.y+64);this.physics.arcade.moveToPointer(a,600);--this.info.ammo}},tryToSpawnEnemies:function(a){this.time.now>this.nextEnemySpawnTime&&200>this.enemies.length&&this.spawnEnemies&&(a=this.enemies.create(this.portal.body.x+Math.floor(201*Math.random()),this.portal.body.y+Math.floor(201*Math.random()),a),this.physics.arcade.enable(a),a.body.bounce.y=.2,a.body.gravity.y=500,a.scale.setTo(Math.floor(2*
Math.random()+2),Math.floor(2*Math.random()+2)),a.animations.add("left",[1,3],1E3,!0),a.animations.add("right",[0,2],1E3,!0),console.log(this.info.monstersKilled),this.nextEnemySpawnTime=20>this.info.monstersKilled?game.time.now+1E3:60>this.info.monstersKilled?game.time.now+800:80>this.info.monstersKilled?game.time.now+600:100>this.info.monstersKilled?game.time.now+400:130>this.info.monstersKilled?game.time.now+300:150>this.info.monstersKilled?game.time.now+200:game.time.now+10,++this.info.totalMonsters,
++this.info.aliveMonsters)},moveEnemies:function(a){a.body.x>this.player.body.x?(a.body.velocity.x=-200,a.animations.play("right")):(a.body.velocity.x=200,a.animations.play("left"))},pollInput:function(){this.player.body.velocity.x=0;this.cursors.left.isDown?(this.player.body.velocity.x=-this.playerSpeed,this.player.animations.play("left"),this.direction="left"):this.cursors.right.isDown?(this.player.body.velocity.x=this.playerSpeed,this.player.animations.play("right"),this.direction="right"):this.player.animations.stop();
this.cursors.up.isDown&&(this.godMode?this.player.body.velocity.y=-500:this.player.body.touching.down&&(this.player.body.velocity.y=-500,this.jumpSound.play()))},reload:function(){this.reloading=!0;this.reloadTime=game.time.now+2E3;this.info.ammo=this.info.maxAmmo}};
